apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-stat-service-dep
  namespace: sys-stat
  labels:
    app: sys-stat-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sys-stat-service
  template:
    metadata:
      labels:
        app: sys-stat-service
    spec:
      containers:
      - name: sys-stat-service
        image: "vipulfadtedev/sys-stat-service:14"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 15