apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-stat-service-dep
  namespace: sys-stat
  labels:
    app: sys-stat-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sys-stat-service
  template:
    metadata:
      labels:
        app: sys-stat-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
    spec:
      containers:
      - name: sys-stat-service
        image: "#image#"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: log-volume
            mountPath: /logs
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: sys-stat-service-nfs-pvc