apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-stat-service-dep
  namespace: sys-stat
  labels:
    app: sys-stat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sys-stat-service
  template:
    metadata:
      labels:
        app: sys-stat-service
    spec:
      containers:
      - name: sys-stat-service
        image: "#image#"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "250Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080