apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: sys-stat-service-hpa
  namespace: sys-stat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sys-stat-service-dep
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 250Mi