apiVersion: v1
kind: PersistentVolume
metadata:
  name: sys-stat-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: sys-stat
    name: sys-stat-service-nfs-pvc
  nfs:
    path: /export/space
    server: 10.0.0.4
    readOnly: false