apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sys-stat-service-nfs-pvc
  namespace: sys-stat
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi