apiVersion: v1
kind: Service
metadata:
  name: sys-stat-service-svc
  namespace: sys-stat
  labels:
    app: sys-stat-service
spec:
  selector:
    app: sys-stat-service
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 8080
  externalIPs:
    - 10.0.0.110